import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import About from "./about";
// import about from "./about"
export default function Home() {
  const router=useRouter()
  const navigate=()=>{
    router.push("/product")
    // router.replace("/product")
  }
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <h1>home page</h1>
        <button onClick={navigate}>navigate button </button>
      </>
    </div>
  );
}
