import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import About from "./about";
// import about from "./about"
export default function Home() {
  const router = useRouter();
  const navigate = () => {
    router.push("/product");
  };
  const { data: session, status } = useSession()
  // if (data) {
    console.log(status,session);
  // }
  const loading = status === "loading"
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>home page</h1>
        {/* <button onClick={navigate}>navigate button </button> */}
        {/* {["1", "2", "3"].map((img) => (
          <Image
            key={img}
            src={`/${img}.jpg`}
            alt="nothing"
            width="300"
            height="400"
          />
        ))} */}

        {!session && !loading && (
          <Link
            href="/api/auth/signin"
            onClick={(e) => {
              e.preventDefault();
              signIn();
            }}
          >
            signin
          </Link>
        )}

        <hr />
        {session && (
          <Link
            href="/api/auth/singout"
            onClick={(e) => {
              e.preventDefault();
              signOut();
            }}
          >
            out
          </Link>
        )}
      </div>
    </div>
  );
}
